development: &default
  #host: "http://es-container:9200"
  host: <%= ENV["ELASTICSEARCH_HOSTS"] %>
  log: true
# test:
#   host: ‘http://elasticsearch:9200'
# production:
#   host: ‘http://www.yourelasticindex:9200'