version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #ports:
    #  - '5432:5432'
    volumes:
      - source-postgres:/var/lib/postgresql/data

  source:
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - ./source:/opt/app
    links:
      - postgres
    ports:
      - '8010:8010'
    env_file:
      - .env
    user: "${UID}:${GID}"

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - source
    ports:
      - '3000:3000'

  redis:
    image: redis

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: ./Dockerfile.sidekiq
    env_file:
      - .env

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    env_file:
      - .env
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  source-postgres:
