source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'bootsnap', require: false
gem 'importmap-rails'
gem 'jbuilder'
gem 'pg'
gem 'rails'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'puma'
gem 'unicorn'
gem "mail", "~> 2.7.1"
gem "redis", "~> 4.5.1"
gem 'sidekiq', "~> 5.2.10"
gem 'connection_pool', "~> 2.3.0"
gem "rack-protection", "~> 3.0.2"
gem "aws-sdk-s3"
gem 'nokogiri', '~> 1.13'
# Elasticsearch integration
gem 'elasticsearch-model'
gem 'elasticsearch-rails'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec-rails'
end

group :development do
  gem 'reek'
  gem 'rubocop'
  gem 'web-console'
end
